const routes = {
  home: '/',
  notFound: '*',
  confirm: '/nhap-ma',
  beNgoan: '/phieu-be-ngoan',
  englishPage: '/english',
  vocabulary: '/vocabulary',
  writing: '/writing',
  listening: '/listening',
  chatWithAI: '/chat-ai',
  test: '/test-page',
  shop: '/tiktok-shop',
  createProduct: '/create-product',
  editProduct: '/edit-product',
  productDetail: '/product-detail',
  examination: '/examination',
  thanhUy: '/thanh-uy',
  template: '/template',
  pageBuider: '/page-builder',
  intro: '/intro',
};
export default routes;
